### ISSUE TITLE
Implement "reserved" state

### ISSUE THREAD

**Issue by dreadwarrior** [dreadwarrior/ahoi-template#4]
- similar to kleinanzeigen
- lightened overlay with dark text
- icon (flag / cross)
- make text color of links to book lighter

**Comment by dreadwarrior** [comment]
ChatGPT Suggestion

**HTML**

```html
<figure class="items-list__item">
  <a href="book.html" class="cover-wrapper">
    <img class="cover"
         src="https://picsum.photos/id/69/148/240"
         width="148" height="240"
         srcset="https://picsum.photos/id/69/148/240 148w,https://picsum.photos/id/69/296/480 296w"
         sizes="(max-width: 768px) 148px, (min-width: 768px) 296px"
         alt="Abbildung des Buchs „The Waste Land“ von Miss Enedina Heidenreich">
    <div class="overlay">
      <span class="overlay-icon">🔍</span>
    </div>
  </a>
  <figcaption class="items-list__item__caption">
    <p><a href="book.html">The Waste Land</a>
      <small class="items-list__item__caption__creator">Miss Enedina Heidenreich</small>
    </p>
  </figcaption>
</figure>
```

**CSS**

```css
.cover-wrapper {
  position: relative;
  display: inline-block;
}

.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.4); /* dunkelgrau halbtransparent */
  display: flex;
  justify-content: center;
  align-items: center;
  pointer-events: none; /* Klicks gehen durch das Overlay zum Link */
}

.overlay-icon {
  color: white;
  font-size: 2rem;
}
```

**Hint**

Mit pointer-events: none im .overlay-Element sorgst du dafür, dass das Overlay den Klick auf den darunterliegenden Link (<a>) nicht blockiert.

**Comment by dreadwarrior** [comment]
ChatGPT Suggestion with pseudo selectors

```css

.cover-wrapper {
  position: relative;
  display: inline-block;
}

/* Overlay-Hintergrund */
.cover-wrapper::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.4); /* halbtransparent schwarz */
  z-index: 1;
  pointer-events: none;
}

/* Icon-Zeichen */
.cover-wrapper::after {
  content: '🔍'; /* oder z. B. '\f002' für FontAwesome */
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 2rem;
  color: white;
  z-index: 2;
  pointer-events: none;
}
```
